INSERT INTO gen_table(create_by, create_time, update_by, update_time, remark, table_id, table_name, table_comment, sub_table_name, sub_table_fk_name, class_name, tpl_category, package_name, module_name, business_name, function_name,
                      function_author, gen_type, gen_path, options)
VALUES (NULL, NULL, NULL, NULL, NULL, 177, 'sys_post', '岗位信息表', NULL, NULL, 'SysPost', 'crud', 'com.ruoyi.project.system', 'system', 'post', '岗位信息', 'ruoyi', NULL, 'src', '{}'),
       (NULL, NULL, NULL, NULL, NULL, 189, 'sys_dict_type', '字典类型表', NULL, NULL, 'SysDictType', 'crud', 'com.ruoyi.project.system', 'system', 'type', '字典类型', 'ruoyi', NULL, 'src', NULL),
       (NULL, NULL, NULL, NULL, NULL, 200, 'sys_dict_data', '字典数据表', NULL, NULL, 'SysDictData', 'crud', 'com.ruoyi.project.system', 'system', 'data', '字典数据', 'ruoyi', NULL, 'src', NULL),
       (NULL, NULL, NULL, NULL, NULL, 188, 'sys_logininfor', '系统访问记录', NULL, NULL, 'SysLogininfor', 'crud', 'com.ruoyi.project.system', 'system', 'logininfor', '系统访问记录', 'ruoyi', NULL, 'src', NULL),
       (NULL, NULL, NULL, NULL, NULL, 197, 'sys_job_log', '定时任务调度日志表', NULL, NULL, 'SysJobLog', 'crud', 'com.ruoyi.project.system', 'system', 'log', '定时任务调度日志', 'ruoyi', NULL, 'src', NULL),
       (NULL, NULL, NULL, NULL, NULL, 190, 'sys_oper_log', '操作日志记录', NULL, NULL, 'SysOperLog', 'crud', 'com.ruoyi.project.system', 'system', 'log', '操作日志记录', 'ruoyi', NULL, 'src', '{}'),
       (NULL, NULL, NULL, NULL, NULL, 186, 'sys_user', '用户信息表', NULL, NULL, 'SysUser', 'crud', 'com.ruoyi.project.system', 'system', 'user', '用户信息', 'ruoyi', NULL, 'src', '{}'),
       (NULL, NULL, NULL, NULL, NULL, 193, 'sys_role_menu', '角色和菜单关联表', NULL, NULL, 'SysRoleMenu', 'crud', 'com.ruoyi.project.system', 'system', 'menu', '角色和菜单关联', 'ruoyi', NULL, 'src', NULL),
       (NULL, NULL, NULL, NULL, NULL, 196, 'sys_job_log', '定时任务调度日志表', NULL, NULL, 'SysJobLog', 'crud', 'com.ruoyi.project.system', 'system', 'log', '定时任务调度日志', 'ruoyi', NULL, 'src', NULL),
       (NULL, NULL, NULL, NULL, NULL, 203, 'sys_job', '定时任务调度表', NULL, NULL, 'SysJob', 'crud', 'com.ruoyi.project.system', 'system', 'job', '定时任务调度', 'ruoyi', NULL, 'src', '{}'),
       (NULL, NULL, NULL, NULL, NULL, 178, 'sys_role', '角色信息表', '', '', 'SysRole', 'crud', 'com.ruoyi.project.system', 'system', 'role', '角色信息', 'ruoyi', NULL, 'src', '{}'),
       (NULL, NULL, NULL, NULL, NULL, 187, 'sys_notice', '通知公告表', NULL, NULL, 'SysNotice', 'crud', 'com.ruoyi.project.system', 'system', 'notice', '通知公告', 'ruoyi', NULL, 'src', '{}'),
       (NULL, NULL, NULL, NULL, NULL, 202, 'sys_role_dept', '角色和部门关联表', NULL, NULL, 'SysRoleDept', 'crud', 'com.ruoyi.project.system', 'system', 'dept', '角色和部门关联', 'ruoyi', NULL, 'src', NULL),
       (NULL, NULL, NULL, NULL, NULL, 191, 'sys_user_post', '用户与岗位关联表', NULL, NULL, 'SysUserPost', 'crud', 'com.ruoyi.project.system', 'system', 'post', '用户与岗位关联', 'ruoyi', NULL, 'src', '{}'),
       (NULL, NULL, NULL, NULL, NULL, 176, 'sys_menu', '菜单权限表', '', '', 'SysMenu', 'tree', 'com.ruoyi.project.system', 'system', 'menu', '菜单权限', 'ruoyi', NULL, 'src', '{"treeCode":"menu_id","treeName":"menu_name",
"treeParentCode":"parent_id"}'),
       (NULL, NULL, NULL, NULL, NULL, 195, 'sys_job_log', '定时任务调度日志表', NULL, NULL, 'SysJobLog', 'crud', 'com.ruoyi.project.system', 'system', 'log', '定时任务调度日志', 'ruoyi', NULL, 'src', NULL),
       (NULL, NULL, NULL, NULL, NULL, 199, 'sys_config', '参数配置表', NULL, NULL, 'SysConfig', 'crud', 'com.ruoyi.project.system', 'system', 'config', '参数配置', 'ruoyi', NULL, 'src', NULL),
       (NULL, NULL, NULL, NULL, NULL, 201, 'sys_dept', '部门表', NULL, NULL, 'SysDept', 'crud', 'com.ruoyi.project.system', 'system', 'dept', '部门', 'ruoyi', NULL, 'src', NULL),
       (NULL, NULL, NULL, NULL, NULL, 194, 'sys_user_role', '用户和角色关联表', NULL, NULL, 'SysUserRole', 'crud', 'com.ruoyi.project.system', 'system', 'role', '用户和角色关联', 'ruoyi', NULL, 'src', NULL);
INSERT INTO gen_table_column(create_by, create_time, update_by, update_time, column_id, table_id, column_name, column_comment, column_type, java_type, java_field, is_pk, is_increment, is_required, is_insert, is_edit, is_list, is_query,
                             query_type, html_type, dict_type, sort)
VALUES (NULL, NULL, NULL, NULL, 1866, 177, 'post_id', '岗位ID', 'bigint(20)', 'Long', 'postId', '1', '1', NULL, NULL, NULL, NULL, NULL, 'EQ', 'input', '', 1),
       (NULL, NULL, NULL, NULL, 1867, 177, 'post_code', '编号', 'varchar(64)', 'String', 'postCode', '0', '0', '1', '1', '1', '1', '1', 'EQ', 'input', '', 2),
       (NULL, NULL, NULL, NULL, 1868, 177, 'post_name', '公共关系维护板块（0 媒体 1 监管部门）', 'varchar(50)', 'String', 'postName', '0', '0', '1', '1', '1', '1', '1', 'EQ', 'radio', '', 3),
       (NULL, NULL, NULL, NULL, 1869, 177, 'post_sort', '性别（0 男 1 女）', 'int(4)', 'Integer', 'postSort', '0', '0', '1', '1', '1', '1', NULL, 'EQ', 'radio', '', 4),
       (NULL, NULL, NULL, NULL, 1870, 177, 'status', '类别（0传统媒体 1自媒体 2网络媒体）', 'char(1)', 'String', 'status', '0', '0', '1', '1', '1', '1', '1', 'EQ', 'radio', '', 5),
       (NULL, NULL, NULL, NULL, 1871, 177, 'create_by', '对接人', 'varchar(64)', 'String', 'createBy', '0', '0', '1', '1', '1', '1', NULL, 'EQ', 'input', '', 6),
       (NULL, NULL, NULL, NULL, 1872, 177, 'create_time', '对业务关注度（0 较高 1 高）', 'datetime', 'String', 'createTime', '0', '0', NULL, '1', '1', '1', NULL, 'EQ', 'radio', '', 7),
       (NULL, NULL, NULL, NULL, 1873, 177, 'update_by', '媒体名称', 'varchar(64)', 'String', 'updateBy', '0', '0', NULL, '1', '1', '1', NULL, 'EQ', 'input', '', 8),
       (NULL, NULL, NULL, NULL, 1874, 177, 'update_time', '更新时间', 'datetime', 'Date', 'updateTime', '0', '0', NULL, NULL, NULL, NULL, NULL, 'EQ', 'datetime', '', 9),
       (NULL, NULL, NULL, NULL, 1875, 177, 'remark', '层级（0 中层 1 基层）', 'varchar(500)', 'String', 'remark', '0', '0', NULL, '1', '1', '1', NULL, 'EQ', 'radio', '', 10),
       (NULL, NULL, NULL, NULL, 1981, 189, 'dict_id', '字典主键', 'bigint(20)', 'Long', 'dictId', '1', '1', NULL, '1', NULL, NULL, NULL, 'EQ', 'input', '', 1),
       (NULL, NULL, NULL, NULL, 1982, 189, 'dict_name', '字典名称', 'varchar(100)', 'String', 'dictName', '0', '0', NULL, '1', '1', '1', '1', 'LIKE', 'input', '', 2),
       (NULL, NULL, NULL, NULL, 1983, 189, 'dict_type', '字典类型', 'varchar(100)', 'String', 'dictType', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'select', '', 3),
       (NULL, NULL, NULL, NULL, 1984, 189, 'status', '状态（0正常 1停用）', 'char(1)', 'String', 'status', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'radio', '', 4),
       (NULL, NULL, NULL, NULL, 1985, 189, 'create_by', '创建者', 'varchar(64)', 'String', 'createBy', '0', '0', NULL, '1', NULL, NULL, NULL, 'EQ', 'input', '', 5),
       (NULL, NULL, NULL, NULL, 1986, 189, 'create_time', '创建时间', 'datetime', 'Date', 'createTime', '0', '0', NULL, '1', NULL, NULL, NULL, 'EQ', 'datetime', '', 6),
       (NULL, NULL, NULL, NULL, 1987, 189, 'update_by', '更新者', 'varchar(64)', 'String', 'updateBy', '0', '0', NULL, '1', '1', NULL, NULL, 'EQ', 'input', '', 7),
       (NULL, NULL, NULL, NULL, 1988, 189, 'update_time', '更新时间', 'datetime', 'Date', 'updateTime', '0', '0', NULL, '1', '1', NULL, NULL, 'EQ', 'datetime', '', 8),
       (NULL, NULL, NULL, NULL, 1989, 189, 'remark', '备注', 'varchar(500)', 'String', 'remark', '0', '0', NULL, '1', '1', '1', NULL, 'EQ', 'textarea', '', 9),
       (NULL, NULL, NULL, NULL, 2058, 200, 'dict_code', '字典编码', 'bigint(20)', 'Long', 'dictCode', '1', '1', NULL, '1', NULL, NULL, NULL, 'EQ', 'input', '', 1),
       (NULL, NULL, NULL, NULL, 2059, 200, 'dict_sort', '字典排序', 'int(4)', 'Integer', 'dictSort', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'input', '', 2),
       (NULL, NULL, NULL, NULL, 2060, 200, 'dict_label', '字典标签', 'varchar(100)', 'String', 'dictLabel', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'input', '', 3),
       (NULL, NULL, NULL, NULL, 2061, 200, 'dict_value', '字典键值', 'varchar(100)', 'String', 'dictValue', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'input', '', 4),
       (NULL, NULL, NULL, NULL, 2062, 200, 'dict_type', '字典类型', 'varchar(100)', 'String', 'dictType', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'select', '', 5),
       (NULL, NULL, NULL, NULL, 2063, 200, 'css_class', '样式属性（其他样式扩展）', 'varchar(100)', 'String', 'cssClass', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'input', '', 6),
       (NULL, NULL, NULL, NULL, 2064, 200, 'list_class', '表格回显样式', 'varchar(100)', 'String', 'listClass', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'input', '', 7),
       (NULL, NULL, NULL, NULL, 2065, 200, 'is_default', '是否默认（Y是 N否）', 'char(1)', 'String', 'isDefault', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'input', '', 8),
       (NULL, NULL, NULL, NULL, 2066, 200, 'status', '状态（0正常 1停用）', 'char(1)', 'String', 'status', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'radio', '', 9),
       (NULL, NULL, NULL, NULL, 2067, 200, 'create_by', '创建者', 'varchar(64)', 'String', 'createBy', '0', '0', NULL, '1', NULL, NULL, NULL, 'EQ', 'input', '', 10),
       (NULL, NULL, NULL, NULL, 2068, 200, 'create_time', '创建时间', 'datetime', 'Date', 'createTime', '0', '0', NULL, '1', NULL, NULL, NULL, 'EQ', 'datetime', '', 11),
       (NULL, NULL, NULL, NULL, 2069, 200, 'update_by', '更新者', 'varchar(64)', 'String', 'updateBy', '0', '0', NULL, '1', '1', NULL, NULL, 'EQ', 'input', '', 12),
       (NULL, NULL, NULL, NULL, 2070, 200, 'update_time', '更新时间', 'datetime', 'Date', 'updateTime', '0', '0', NULL, '1', '1', NULL, NULL, 'EQ', 'datetime', '', 13),
       (NULL, NULL, NULL, NULL, 2071, 200, 'remark', '备注', 'varchar(500)', 'String', 'remark', '0', '0', NULL, '1', '1', '1', NULL, 'EQ', 'textarea', '', 14),
       (NULL, NULL, NULL, NULL, 1972, 188, 'info_id', '访问ID', 'bigint(20)', 'Long', 'infoId', '1', '1', NULL, '1', NULL, NULL, NULL, 'EQ', 'input', '', 1),
       (NULL, NULL, NULL, NULL, 1973, 188, 'user_name', '用户账号', 'varchar(50)', 'String', 'userName', '0', '0', NULL, '1', '1', '1', '1', 'LIKE', 'input', '', 2),
       (NULL, NULL, NULL, NULL, 1974, 188, 'ipaddr', '登录IP地址', 'varchar(128)', 'String', 'ipaddr', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'input', '', 3),
       (NULL, NULL, NULL, NULL, 1975, 188, 'login_location', '登录地点', 'varchar(255)', 'String', 'loginLocation', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'input', '', 4),
       (NULL, NULL, NULL, NULL, 1976, 188, 'browser', '浏览器类型', 'varchar(50)', 'String', 'browser', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'input', '', 5),
       (NULL, NULL, NULL, NULL, 1977, 188, 'os', '操作系统', 'varchar(50)', 'String', 'os', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'input', '', 6),
       (NULL, NULL, NULL, NULL, 1978, 188, 'status', '登录状态（0成功 1失败）', 'char(1)', 'String', 'status', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'radio', '', 7),
       (NULL, NULL, NULL, NULL, 1979, 188, 'msg', '提示消息', 'varchar(255)', 'String', 'msg', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'input', '', 8),
       (NULL, NULL, NULL, NULL, 1980, 188, 'login_time', '访问时间', 'datetime', 'Date', 'loginTime', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'datetime', '', 9),
       (NULL, NULL, NULL, NULL, 2030, 197, 'job_log_id', '任务日志ID', 'bigint(20)', 'Long', 'jobLogId', '1', '1', NULL, '1', NULL, NULL, NULL, 'EQ', 'input', '', 1),
       (NULL, NULL, NULL, NULL, 2031, 197, 'job_name', '任务名称', 'varchar(64)', 'String', 'jobName', '0', '0', '1', '1', '1', '1', '1', 'LIKE', 'input', '', 2),
       (NULL, NULL, NULL, NULL, 2032, 197, 'job_group', '任务组名', 'varchar(64)', 'String', 'jobGroup', '0', '0', '1', '1', '1', '1', '1', 'EQ', 'input', '', 3),
       (NULL, NULL, NULL, NULL, 2033, 197, 'invoke_target', '调用目标字符串', 'varchar(500)', 'String', 'invokeTarget', '0', '0', '1', '1', '1', '1', '1', 'EQ', 'textarea', '', 4),
       (NULL, NULL, NULL, NULL, 2034, 197, 'job_message', '日志信息', 'varchar(500)', 'String', 'jobMessage', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'textarea', '', 5),
       (NULL, NULL, NULL, NULL, 2035, 197, 'status', '执行状态（0正常 1失败）', 'char(1)', 'String', 'status', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'radio', '', 6),
       (NULL, NULL, NULL, NULL, 2036, 197, 'exception_info', '异常信息', 'varchar(2000)', 'String', 'exceptionInfo', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'textarea', '', 7),
       (NULL, NULL, NULL, NULL, 2037, 197, 'create_time', '创建时间', 'datetime', 'Date', 'createTime', '0', '0', NULL, '1', NULL, NULL, NULL, 'EQ', 'datetime', '', 8),
       (NULL, NULL, NULL, NULL, 1990, 190, 'oper_id', '日志主键', 'bigint(20)', 'Long', 'operId', '1', '1', NULL, '1', NULL, NULL, NULL, 'EQ', 'input', 'sys_user_sex', 1),
       (NULL, NULL, NULL, NULL, 1991, 190, 'title', '模块标题', 'varchar(50)', 'String', 'title', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'input', '', 2),
       (NULL, NULL, NULL, NULL, 1992, 190, 'business_type', '业务类型（0其它 1新增 2修改 3删除）', 'int(2)', 'Integer', 'businessType', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'select', '', 3),
       (NULL, NULL, NULL, NULL, 1993, 190, 'method', '方法名称', 'varchar(100)', 'String', 'method', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'input', '', 4),
       (NULL, NULL, NULL, NULL, 1994, 190, 'request_method', '请求方式', 'varchar(10)', 'String', 'requestMethod', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'input', '', 5),
       (NULL, NULL, NULL, NULL, 1995, 190, 'operator_type', '操作类别（0其它 1后台用户 2手机端用户）', 'int(1)', 'Integer', 'operatorType', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'select', '', 6),
       (NULL, NULL, NULL, NULL, 1996, 190, 'oper_name', '操作人员', 'varchar(50)', 'String', 'operName', '0', '0', NULL, '1', '1', '1', '1', 'LIKE', 'input', '', 7),
       (NULL, NULL, NULL, NULL, 1997, 190, 'dept_name', '部门名称', 'varchar(50)', 'String', 'deptName', '0', '0', NULL, '1', '1', '1', '1', 'LIKE', 'input', '', 8),
       (NULL, NULL, NULL, NULL, 1998, 190, 'oper_url', '请求URL', 'varchar(255)', 'String', 'operUrl', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'input', '', 9),
       (NULL, NULL, NULL, NULL, 1999, 190, 'oper_ip', '主机地址', 'varchar(128)', 'String', 'operIp', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'input', '', 10),
       (NULL, NULL, NULL, NULL, 2000, 190, 'oper_location', '操作地点', 'varchar(255)', 'String', 'operLocation', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'input', '', 11),
       (NULL, NULL, NULL, NULL, 2001, 190, 'oper_param', '请求参数', 'varchar(2000)', 'String', 'operParam', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'textarea', '', 12),
       (NULL, NULL, NULL, NULL, 2002, 190, 'json_result', '返回参数', 'varchar(2000)', 'String', 'jsonResult', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'textarea', '', 13),
       (NULL, NULL, NULL, NULL, 2003, 190, 'status', '操作状态（0正常 1异常）', 'int(1)', 'Integer', 'status', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'radio', '', 14),
       (NULL, NULL, NULL, NULL, 2004, 190, 'error_msg', '错误消息', 'varchar(2000)', 'String', 'errorMsg', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'textarea', '', 15),
       (NULL, NULL, NULL, NULL, 2005, 190, 'oper_time', '操作时间', 'datetime', 'Date', 'operTime', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'datetime', '', 16),
       (NULL, NULL, NULL, NULL, 1943, 186, 'user_id', '用户ID', 'bigint(20)', 'Long', 'userId', '1', '1', NULL, NULL, NULL, NULL, NULL, 'EQ', 'input', '', 1),
       (NULL, NULL, NULL, NULL, 1944, 186, 'dept_id', '部门ID', 'bigint(20)', 'Long', 'deptId', '0', '0', NULL, NULL, NULL, '1', '1', 'EQ', 'input', '', 2),
       (NULL, NULL, NULL, NULL, 1945, 186, 'user_name', '用户账号', 'varchar(30)', 'String', 'userName', '0', '0', '1', '1', '1', '1', '1', 'LIKE', 'input', '', 3),
       (NULL, NULL, NULL, NULL, 1946, 186, 'nick_name', '用户昵称', 'varchar(30)', 'String', 'nickName', '0', '0', '1', '1', '1', '1', '1', 'LIKE', 'input', '', 4),
       (NULL, NULL, NULL, NULL, 1947, 186, 'user_type', '用户类型（00系统用户）', 'varchar(2)', 'String', 'userType', '0', '0', NULL, NULL, NULL, '1', '1', 'EQ', 'select', '', 5),
       (NULL, NULL, NULL, NULL, 1948, 186, 'email', '用户邮箱', 'varchar(50)', 'String', 'email', '0', '0', NULL, NULL, NULL, '1', '1', 'EQ', 'input', '', 6),
       (NULL, NULL, NULL, NULL, 1949, 186, 'phonenumber', '手机号码', 'varchar(11)', 'String', 'phonenumber', '0', '0', NULL, NULL, NULL, '1', '1', 'EQ', 'input', '', 7),
       (NULL, NULL, NULL, NULL, 1950, 186, 'sex', '用户性别（0男 1女 2未知）', 'char(1)', 'String', 'sex', '0', '0', NULL, NULL, NULL, '1', '1', 'EQ', 'select', 'sys_user_sex', 8),
       (NULL, NULL, NULL, NULL, 1951, 186, 'avatar', '头像地址', 'varchar(100)', 'String', 'avatar', '0', '0', NULL, NULL, NULL, '1', '1', 'EQ', 'input', '', 9),
       (NULL, NULL, NULL, NULL, 1952, 186, 'password', '密码', 'varchar(100)', 'String', 'password', '0', '0', NULL, NULL, NULL, '1', '1', 'EQ', 'input', '', 10),
       (NULL, NULL, NULL, NULL, 1953, 186, 'status', '帐号状态（0正常 1停用）', 'char(1)', 'String', 'status', '0', '0', NULL, NULL, NULL, '1', '1', 'EQ', 'radio', '', 11),
       (NULL, NULL, NULL, NULL, 1954, 186, 'del_flag', '删除标志（0代表存在 2代表删除）', 'char(1)', 'String', 'delFlag', '0', '0', NULL, NULL, NULL, NULL, NULL, 'EQ', 'input', '', 12),
       (NULL, NULL, NULL, NULL, 1955, 186, 'login_ip', '最后登录IP', 'varchar(128)', 'String', 'loginIp', '0', '0', NULL, NULL, NULL, '1', '1', 'EQ', 'input', '', 13),
       (NULL, NULL, NULL, NULL, 1956, 186, 'login_date', '最后登录时间', 'datetime', 'Date', 'loginDate', '0', '0', NULL, NULL, NULL, '1', '1', 'EQ', 'datetime', '', 14),
       (NULL, NULL, NULL, NULL, 1957, 186, 'create_by', '创建者', 'varchar(64)', 'String', 'createBy', '0', '0', NULL, NULL, NULL, NULL, NULL, 'EQ', 'input', '', 15),
       (NULL, NULL, NULL, NULL, 1958, 186, 'create_time', '创建时间', 'datetime', 'Date', 'createTime', '0', '0', NULL, NULL, NULL, NULL, NULL, 'EQ', 'datetime', '', 16),
       (NULL, NULL, NULL, NULL, 1959, 186, 'update_by', '更新者', 'varchar(64)', 'String', 'updateBy', '0', '0', NULL, NULL, NULL, NULL, NULL, 'EQ', 'input', '', 17),
       (NULL, NULL, NULL, NULL, 1960, 186, 'update_time', '更新时间', 'datetime', 'Date', 'updateTime', '0', '0', NULL, NULL, NULL, NULL, NULL, 'EQ', 'datetime', '', 18),
       (NULL, NULL, NULL, NULL, 1961, 186, 'remark', '备注', 'varchar(500)', 'String', 'remark', '0', '0', NULL, NULL, NULL, '1', NULL, 'EQ', 'textarea', '', 19),
       (NULL, NULL, NULL, NULL, 2010, 193, 'role_id', '角色ID', 'bigint(20)', 'Long', 'roleId', '1', '0', NULL, '1', NULL, NULL, NULL, 'EQ', 'input', '', 1),
       (NULL, NULL, NULL, NULL, 2011, 193, 'menu_id', '菜单ID', 'bigint(20)', 'Long', 'menuId', '1', '0', NULL, '1', NULL, NULL, NULL, 'EQ', 'input', '', 2),
       (NULL, NULL, NULL, NULL, 2022, 196, 'job_log_id', '任务日志ID', 'bigint(20)', 'Long', 'jobLogId', '1', '1', NULL, '1', NULL, NULL, NULL, 'EQ', 'input', '', 1),
       (NULL, NULL, NULL, NULL, 2023, 196, 'job_name', '任务名称', 'varchar(64)', 'String', 'jobName', '0', '0', '1', '1', '1', '1', '1', 'LIKE', 'input', '', 2),
       (NULL, NULL, NULL, NULL, 2024, 196, 'job_group', '任务组名', 'varchar(64)', 'String', 'jobGroup', '0', '0', '1', '1', '1', '1', '1', 'EQ', 'input', '', 3),
       (NULL, NULL, NULL, NULL, 2025, 196, 'invoke_target', '调用目标字符串', 'varchar(500)', 'String', 'invokeTarget', '0', '0', '1', '1', '1', '1', '1', 'EQ', 'textarea', '', 4),
       (NULL, NULL, NULL, NULL, 2026, 196, 'job_message', '日志信息', 'varchar(500)', 'String', 'jobMessage', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'textarea', '', 5),
       (NULL, NULL, NULL, NULL, 2027, 196, 'status', '执行状态（0正常 1失败）', 'char(1)', 'String', 'status', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'radio', '', 6),
       (NULL, NULL, NULL, NULL, 2028, 196, 'exception_info', '异常信息', 'varchar(2000)', 'String', 'exceptionInfo', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'textarea', '', 7),
       (NULL, NULL, NULL, NULL, 2029, 196, 'create_time', '创建时间', 'datetime', 'Date', 'createTime', '0', '0', NULL, '1', NULL, NULL, NULL, 'EQ', 'datetime', '', 8),
       (NULL, NULL, NULL, NULL, 2088, 203, 'job_id', '任务ID', 'bigint(20)', 'Long', 'jobId', '1', '1', NULL, NULL, NULL, NULL, NULL, 'EQ', 'input', '', 1),
       (NULL, NULL, NULL, NULL, 2089, 203, 'job_name', '任务名称', 'varchar(64)', 'String', 'jobName', '1', '0', NULL, '1', NULL, NULL, NULL, 'LIKE', 'input', '', 2),
       (NULL, NULL, NULL, NULL, 2090, 203, 'job_group', '任务组名', 'varchar(64)', 'String', 'jobGroup', '1', '0', NULL, NULL, NULL, NULL, NULL, 'EQ', 'input', '', 3),
       (NULL, NULL, NULL, NULL, 2091, 203, 'invoke_target', '调用目标字符串', 'varchar(500)', 'String', 'invokeTarget', '0', '0', '1', '1', '1', '1', '1', 'EQ', 'textarea', '', 4),
       (NULL, NULL, NULL, NULL, 2092, 203, 'cron_expression', 'cron执行表达式', 'varchar(255)', 'String', 'cronExpression', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'input', '', 5),
       (NULL, NULL, NULL, NULL, 2093, 203, 'misfire_policy', '计划执行错误策略（1立即执行 2执行一次 3放弃执行）', 'varchar(20)', 'String', 'misfirePolicy', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'input', '', 6),
       (NULL, NULL, NULL, NULL, 2094, 203, 'concurrent', '是否并发执行（0允许 1禁止）', 'char(1)', 'String', 'concurrent', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'input', '', 7),
       (NULL, NULL, NULL, NULL, 2095, 203, 'status', '状态（0正常 1暂停）', 'char(1)', 'String', 'status', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'radio', '', 8),
       (NULL, NULL, NULL, NULL, 2096, 203, 'create_by', '创建者', 'varchar(64)', 'String', 'createBy', '0', '0', NULL, '1', NULL, NULL, NULL, 'EQ', 'input', '', 9),
       (NULL, NULL, NULL, NULL, 2097, 203, 'create_time', '创建时间', 'datetime', 'Date', 'createTime', '0', '0', NULL, '1', NULL, NULL, NULL, 'EQ', 'datetime', '', 10),
       (NULL, NULL, NULL, NULL, 2098, 203, 'update_by', '更新者', 'varchar(64)', 'String', 'updateBy', '0', '0', NULL, '1', '1', NULL, NULL, 'EQ', 'input', '', 11),
       (NULL, NULL, NULL, NULL, 2099, 203, 'update_time', '更新时间', 'datetime', 'Date', 'updateTime', '0', '0', NULL, '1', '1', NULL, NULL, 'EQ', 'datetime', '', 12),
       (NULL, NULL, NULL, NULL, 2100, 203, 'remark', '备注信息', 'varchar(500)', 'String', 'remark', '0', '0', NULL, '1', '1', '1', NULL, 'EQ', 'textarea', '', 13),
       (NULL, NULL, NULL, NULL, 1876, 178, 'role_id', '角色ID', 'bigint(20)', 'Long', 'roleId', '1', '1', NULL, '1', NULL, NULL, NULL, 'EQ', 'input', '', 1),
       (NULL, NULL, NULL, NULL, 1877, 178, 'role_name', '角色名称', 'varchar(30)', 'String', 'roleName', '0', '0', '1', '1', '1', '1', '1', 'LIKE', 'input', '', 2),
       (NULL, NULL, NULL, NULL, 1878, 178, 'role_key', '角色权限字符串', 'varchar(100)', 'String', 'roleKey', '0', '0', '1', '1', '1', '1', '1', 'EQ', 'input', '', 3),
       (NULL, NULL, NULL, NULL, 1879, 178, 'role_sort', '显示顺序', 'int(4)', 'Integer', 'roleSort', '0', '0', '1', '1', '1', '1', '1', 'EQ', 'input', '', 4),
       (NULL, NULL, NULL, NULL, 1880, 178, 'data_scope', '数据范围（1：全部数据权限 2：自定数据权限 3：本部门数据权限 4：本部门及以下数据权限）', 'char(1)', 'String', 'dataScope', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'input', '', 5),
       (NULL, NULL, NULL, NULL, 1881, 178, 'menu_check_strictly', '菜单树选择项是否关联显示', 'tinyint(1)', 'Integer', 'menuCheckStrictly', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'input', '', 6),
       (NULL, NULL, NULL, NULL, 1882, 178, 'dept_check_strictly', '部门树选择项是否关联显示', 'tinyint(1)', 'Integer', 'deptCheckStrictly', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'input', '', 7),
       (NULL, NULL, NULL, NULL, 1883, 178, 'status', '角色状态（0正常 1停用）', 'char(1)', 'String', 'status', '0', '0', '1', '1', '1', '1', '1', 'EQ', 'radio', '', 8),
       (NULL, NULL, NULL, NULL, 1884, 178, 'del_flag', '删除标志（0代表存在 2代表删除）', 'char(1)', 'String', 'delFlag', '0', '0', NULL, '1', NULL, NULL, NULL, 'EQ', 'input', '', 9),
       (NULL, NULL, NULL, NULL, 1885, 178, 'create_by', '创建者', 'varchar(64)', 'String', 'createBy', '0', '0', NULL, '1', NULL, NULL, NULL, 'EQ', 'input', '', 10),
       (NULL, NULL, NULL, NULL, 1886, 178, 'create_time', '创建时间', 'datetime', 'Date', 'createTime', '0', '0', NULL, '1', NULL, NULL, NULL, 'EQ', 'datetime', '', 11),
       (NULL, NULL, NULL, NULL, 1887, 178, 'update_by', '更新者', 'varchar(64)', 'String', 'updateBy', '0', '0', NULL, '1', '1', NULL, NULL, 'EQ', 'input', '', 12),
       (NULL, NULL, NULL, NULL, 1888, 178, 'update_time', '更新时间', 'datetime', 'Date', 'updateTime', '0', '0', NULL, '1', '1', NULL, NULL, 'EQ', 'datetime', '', 13),
       (NULL, NULL, NULL, NULL, 1889, 178, 'remark', '备注', 'varchar(500)', 'String', 'remark', '0', '0', NULL, '1', '1', '1', NULL, 'EQ', 'textarea', '', 14),
       (NULL, NULL, NULL, NULL, 1962, 187, 'notice_id', '公告ID', 'int(4)', 'Integer', 'noticeId', '1', '1', NULL, '1', NULL, NULL, NULL, 'EQ', 'input', '', 1),
       (NULL, NULL, NULL, NULL, 1963, 187, 'notice_title', '公告标题', 'varchar(50)', 'String', 'noticeTitle', '0', '0', '1', '1', '1', '1', '1', 'EQ', 'imageUpload', '', 2),
       (NULL, NULL, NULL, NULL, 1964, 187, 'notice_type', '公告类型（1通知 2公告）', 'char(1)', 'String', 'noticeType', '0', '0', '1', '1', '1', '1', '1', 'EQ', 'select', '', 3),
       (NULL, NULL, NULL, NULL, 1965, 187, 'notice_content', '公告内容', 'longblob', 'String', 'noticeContent', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'editor', '', 4),
       (NULL, NULL, NULL, NULL, 1966, 187, 'status', '公告状态（0正常 1关闭）', 'char(1)', 'String', 'status', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'radio', '', 5),
       (NULL, NULL, NULL, NULL, 1967, 187, 'create_by', '创建者', 'varchar(64)', 'String', 'createBy', '0', '0', NULL, '1', NULL, NULL, NULL, 'EQ', 'input', '', 6),
       (NULL, NULL, NULL, NULL, 1968, 187, 'create_time', '创建时间', 'datetime', 'Date', 'createTime', '0', '0', NULL, '1', NULL, NULL, NULL, 'EQ', 'datetime', '', 7),
       (NULL, NULL, NULL, NULL, 1969, 187, 'update_by', '更新者', 'varchar(64)', 'String', 'updateBy', '0', '0', NULL, '1', '1', NULL, NULL, 'EQ', 'input', '', 8),
       (NULL, NULL, NULL, NULL, 1970, 187, 'update_time', '更新时间', 'datetime', 'Date', 'updateTime', '0', '0', NULL, '1', '1', NULL, NULL, 'EQ', 'datetime', '', 9),
       (NULL, NULL, NULL, NULL, 1971, 187, 'remark', '备注', 'varchar(255)', 'String', 'remark', '0', '0', NULL, '1', '1', '1', NULL, 'EQ', 'input', '', 10),
       (NULL, NULL, NULL, NULL, 2086, 202, 'role_id', '角色ID', 'bigint(20)', 'Long', 'roleId', '1', '0', NULL, '1', NULL, NULL, NULL, 'EQ', 'input', '', 1),
       (NULL, NULL, NULL, NULL, 2087, 202, 'dept_id', '部门ID', 'bigint(20)', 'Long', 'deptId', '1', '0', NULL, '1', NULL, NULL, NULL, 'EQ', 'input', '', 2),
       (NULL, NULL, NULL, NULL, 2006, 191, 'user_id', '用户ID', 'bigint(20)', 'Long', 'userId1', '1', '0', NULL, '1', NULL, NULL, NULL, 'EQ', 'input', '', 1),
       (NULL, NULL, NULL, NULL, 2007, 191, 'post_id', '岗位ID', 'bigint(20)', 'Long', 'postId', '1', '0', NULL, '1', NULL, NULL, NULL, 'EQ', 'input', '', 2),
       (NULL, NULL, NULL, NULL, 1847, 176, 'menu_id', '菜单ID', 'bigint(20)', 'Long', 'menuId', '1', '1', NULL, '1', NULL, NULL, NULL, 'EQ', 'input', '', 1),
       (NULL, NULL, NULL, NULL, 1848, 176, 'menu_name', '菜单名称', 'varchar(50)', 'String', 'menuName', '0', '0', '1', '1', '1', '1', '1', 'LIKE', 'fileUpload', '', 2),
       (NULL, NULL, NULL, NULL, 1849, 176, 'parent_id', '父菜单ID', 'bigint(20)', 'Long', 'parentId', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'input', '', 3),
       (NULL, NULL, NULL, NULL, 1850, 176, 'order_num', '显示顺序', 'int(4)', 'Integer', 'orderNum', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'input', '', 4),
       (NULL, NULL, NULL, NULL, 1851, 176, 'path', '路由地址', 'varchar(200)', 'String', 'path', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'input', '', 5),
       (NULL, NULL, NULL, NULL, 1852, 176, 'component', '组件路径', 'varchar(255)', 'String', 'component', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'input', '', 6),
       (NULL, NULL, NULL, NULL, 1853, 176, 'query', '路由参数', 'varchar(255)', 'String', 'query', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'input', '', 7),
       (NULL, NULL, NULL, NULL, 1854, 176, 'is_frame', '是否为外链（0是 1否）', 'int(1)', 'Integer', 'isFrame', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'input', '', 8),
       (NULL, NULL, NULL, NULL, 1855, 176, 'is_cache', '是否缓存（0缓存 1不缓存）', 'int(1)', 'Integer', 'isCache', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'input', '', 9),
       (NULL, NULL, NULL, NULL, 1856, 176, 'menu_type', '菜单类型（M目录 C菜单 F按钮）', 'char(1)', 'String', 'menuType', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'select', '', 10),
       (NULL, NULL, NULL, NULL, 1857, 176, 'visible', '菜单状态（0显示 1隐藏）', 'char(1)', 'String', 'visible', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'input', '', 11),
       (NULL, NULL, NULL, NULL, 1858, 176, 'status', '菜单状态（0正常 1停用）', 'char(1)', 'String', 'status', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'radio', '', 12),
       (NULL, NULL, NULL, NULL, 1859, 176, 'perms', '权限标识', 'varchar(100)', 'String', 'perms', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'input', '', 13),
       (NULL, NULL, NULL, NULL, 1860, 176, 'icon', '菜单图标', 'varchar(100)', 'String', 'icon', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'imageUpload', '', 14),
       (NULL, NULL, NULL, NULL, 1861, 176, 'create_by', '创建者', 'varchar(64)', 'String', 'createBy', '0', '0', NULL, '1', NULL, NULL, NULL, 'EQ', 'input', '', 15),
       (NULL, NULL, NULL, NULL, 1862, 176, 'create_time', '创建时间', 'datetime', 'Date', 'createTime', '0', '0', NULL, '1', NULL, NULL, NULL, 'EQ', 'datetime', '', 16),
       (NULL, NULL, NULL, NULL, 1863, 176, 'update_by', '更新者', 'varchar(64)', 'String', 'updateBy', '0', '0', NULL, '1', '1', NULL, NULL, 'EQ', 'input', '', 17),
       (NULL, NULL, NULL, NULL, 1864, 176, 'update_time', '更新时间', 'datetime', 'Date', 'updateTime', '0', '0', NULL, '1', '1', NULL, NULL, 'EQ', 'datetime', '', 18),
       (NULL, NULL, NULL, NULL, 1865, 176, 'remark', '备注', 'varchar(500)', 'String', 'remark', '0', '0', NULL, '1', '1', '1', NULL, 'EQ', 'textarea', '', 19),
       (NULL, NULL, NULL, NULL, 2014, 195, 'job_log_id', '任务日志ID', 'bigint(20)', 'Long', 'jobLogId', '1', '1', NULL, '1', NULL, NULL, NULL, 'EQ', 'input', '', 1),
       (NULL, NULL, NULL, NULL, 2015, 195, 'job_name', '任务名称', 'varchar(64)', 'String', 'jobName', '0', '0', '1', '1', '1', '1', '1', 'LIKE', 'input', '', 2),
       (NULL, NULL, NULL, NULL, 2016, 195, 'job_group', '任务组名', 'varchar(64)', 'String', 'jobGroup', '0', '0', '1', '1', '1', '1', '1', 'EQ', 'input', '', 3),
       (NULL, NULL, NULL, NULL, 2017, 195, 'invoke_target', '调用目标字符串', 'varchar(500)', 'String', 'invokeTarget', '0', '0', '1', '1', '1', '1', '1', 'EQ', 'textarea', '', 4),
       (NULL, NULL, NULL, NULL, 2018, 195, 'job_message', '日志信息', 'varchar(500)', 'String', 'jobMessage', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'textarea', '', 5),
       (NULL, NULL, NULL, NULL, 2019, 195, 'status', '执行状态（0正常 1失败）', 'char(1)', 'String', 'status', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'radio', '', 6),
       (NULL, NULL, NULL, NULL, 2020, 195, 'exception_info', '异常信息', 'varchar(2000)', 'String', 'exceptionInfo', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'textarea', '', 7),
       (NULL, NULL, NULL, NULL, 2021, 195, 'create_time', '创建时间', 'datetime', 'Date', 'createTime', '0', '0', NULL, '1', NULL, NULL, NULL, 'EQ', 'datetime', '', 8),
       (NULL, NULL, NULL, NULL, 2048, 199, 'config_id', '参数主键', 'int(5)', 'Integer', 'configId', '1', '1', NULL, '1', NULL, NULL, NULL, 'EQ', 'input', '', 1),
       (NULL, NULL, NULL, NULL, 2049, 199, 'config_name', '参数名称', 'varchar(100)', 'String', 'configName', '0', '0', NULL, '1', '1', '1', '1', 'LIKE', 'input', '', 2),
       (NULL, NULL, NULL, NULL, 2050, 199, 'config_key', '参数键名', 'varchar(100)', 'String', 'configKey', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'input', '', 3),
       (NULL, NULL, NULL, NULL, 2051, 199, 'config_value', '参数键值', 'varchar(500)', 'String', 'configValue', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'textarea', '', 4),
       (NULL, NULL, NULL, NULL, 2052, 199, 'config_type', '系统内置（Y是 N否）', 'char(1)', 'String', 'configType', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'select', '', 5),
       (NULL, NULL, NULL, NULL, 2053, 199, 'create_by', '创建者', 'varchar(64)', 'String', 'createBy', '0', '0', NULL, '1', NULL, NULL, NULL, 'EQ', 'input', '', 6),
       (NULL, NULL, NULL, NULL, 2054, 199, 'create_time', '创建时间', 'datetime', 'Date', 'createTime', '0', '0', NULL, '1', NULL, NULL, NULL, 'EQ', 'datetime', '', 7),
       (NULL, NULL, NULL, NULL, 2055, 199, 'update_by', '更新者', 'varchar(64)', 'String', 'updateBy', '0', '0', NULL, '1', '1', NULL, NULL, 'EQ', 'input', '', 8),
       (NULL, NULL, NULL, NULL, 2056, 199, 'update_time', '更新时间', 'datetime', 'Date', 'updateTime', '0', '0', NULL, '1', '1', NULL, NULL, 'EQ', 'datetime', '', 9),
       (NULL, NULL, NULL, NULL, 2057, 199, 'remark', '备注', 'varchar(500)', 'String', 'remark', '0', '0', NULL, '1', '1', '1', NULL, 'EQ', 'textarea', '', 10),
       (NULL, NULL, NULL, NULL, 2072, 201, 'dept_id', '部门id', 'bigint(20)', 'Long', 'deptId', '1', '1', NULL, '1', NULL, NULL, NULL, 'EQ', 'input', '', 1),
       (NULL, NULL, NULL, NULL, 2073, 201, 'parent_id', '父部门id', 'bigint(20)', 'Long', 'parentId', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'input', '', 2),
       (NULL, NULL, NULL, NULL, 2074, 201, 'ancestors', '祖级列表', 'varchar(50)', 'String', 'ancestors', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'input', '', 3),
       (NULL, NULL, NULL, NULL, 2075, 201, 'dept_name', '部门名称', 'varchar(30)', 'String', 'deptName', '0', '0', NULL, '1', '1', '1', '1', 'LIKE', 'input', '', 4),
       (NULL, NULL, NULL, NULL, 2076, 201, 'order_num', '显示顺序', 'int(4)', 'Integer', 'orderNum', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'input', '', 5),
       (NULL, NULL, NULL, NULL, 2077, 201, 'leader', '负责人', 'varchar(20)', 'String', 'leader', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'input', '', 6),
       (NULL, NULL, NULL, NULL, 2078, 201, 'phone', '联系电话', 'varchar(11)', 'String', 'phone', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'input', '', 7),
       (NULL, NULL, NULL, NULL, 2079, 201, 'email', '邮箱', 'varchar(50)', 'String', 'email', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'input', '', 8),
       (NULL, NULL, NULL, NULL, 2080, 201, 'status', '部门状态（0正常 1停用）', 'char(1)', 'String', 'status', '0', '0', NULL, '1', '1', '1', '1', 'EQ', 'radio', '', 9),
       (NULL, NULL, NULL, NULL, 2081, 201, 'del_flag', '删除标志（0代表存在 2代表删除）', 'char(1)', 'String', 'delFlag', '0', '0', NULL, '1', NULL, NULL, NULL, 'EQ', 'input', '', 10),
       (NULL, NULL, NULL, NULL, 2082, 201, 'create_by', '创建者', 'varchar(64)', 'String', 'createBy', '0', '0', NULL, '1', NULL, NULL, NULL, 'EQ', 'input', '', 11),
       (NULL, NULL, NULL, NULL, 2083, 201, 'create_time', '创建时间', 'datetime', 'Date', 'createTime', '0', '0', NULL, '1', NULL, NULL, NULL, 'EQ', 'datetime', '', 12),
       (NULL, NULL, NULL, NULL, 2084, 201, 'update_by', '更新者', 'varchar(64)', 'String', 'updateBy', '0', '0', NULL, '1', '1', NULL, NULL, 'EQ', 'input', '', 13),
       (NULL, NULL, NULL, NULL, 2085, 201, 'update_time', '更新时间', 'datetime', 'Date', 'updateTime', '0', '0', NULL, '1', '1', NULL, NULL, 'EQ', 'datetime', '', 14),
       (NULL, NULL, NULL, NULL, 2012, 194, 'user_id', '用户ID', 'bigint(20)', 'Long', 'userId', '1', '0', NULL, '1', NULL, NULL, NULL, 'EQ', 'input', '', 1),
       (NULL, NULL, NULL, NULL, 2013, 194, 'role_id', '角色ID', 'bigint(20)', 'Long', 'roleId', '1', '0', NULL, '1', NULL, NULL, NULL, 'EQ', 'input', '', 2);
